import { Providers } from "@/components/providers/Provider";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "TV / Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers attribute="class" defaultTheme="light" enableSystem>
          {children}
        </Providers>
      </body>
    </html>
  );
}
